name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        node: ["12.x", "14.x", "16.x", "17.x"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Installing node ${{matrix.node}} on ${{matrix.os}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - run: npm ci
      - name: Building...
        run: npm run build
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
