name: Code Quality
on: push

jobs:
  styles:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["lts/erbium", "lts/fermium", "lts/*"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm run format:check
  lint:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["lts/erbium", "lts/fermium", "lts/*"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm run lint
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["lts/erbium", "lts/fermium", "lts/*"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm run build
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        node: ["lts/erbium", "lts/fermium", "lts/*"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
          cache: "npm"
      - run: npm ci
      - run: npm test
